dataloader:
  _target_: earthtext.datamodules.chipmultilabel.ChipMultilabelModule
  metadata_file:  /opt/data/california-naip-chips/california-naip-chips-100k.parquet 
  get_osm_strlabels: True
  get_osm_ohearea: True
  get_osm_ohecount: True
  get_osm_ohelength: True
  embeddings_normalization: True
  multilabel_threshold_osm_ohecount: 1
  osmvector_normalization: True
  batch_size: 8
  num_workers: 10

model:
  _target_: earthtext.models.osmencoder.OSMEncoder
  output_dim: 768
  layers_spec: [4096, 4096]
  use_osm_counts: True
  use_osm_lengths: True    
  use_osm_areas: True    
  activation_fn: 'relu'
  osm_codeset: 'naip'

training:
  loss: 'rmse'
  epochs: 1
