dataloader:
  _target_: earthtext.datamodules.chipmultilabel.ChipMultilabelModule
  metadata_file:  /opt/data/california-naip-chips/california-naip-chips-100k.parquet
  neighbor_embeddings_folder: /opt/data/california-naip-chips/california-naip-chips-100k-neighbours/npy
  neighborhood_radius: 8  # max 8
  get_osm_strlabels: True
  get_osm_ohearea: True
  get_osm_ohecount: True
  get_osm_ohelength: True
  get_chip_id: True
  embeddings_normalization: True
  osmvector_normalization: False
  # multilabel_threshold_osm_ohecount: 1
  multilabel_threshold_osm_ohearea: 1
  batch_size: 16
  pin_memory: True
  num_workers: 4
  
model:
  _target_: earthtext.models.multilabel.MultisizeContextualCNN
  input_dim: 768
  output_dim: 140
  layers_spec: [512, 256, 128]
  activation_fn: 'relu'
  # channel_specific: True
  # osm_codeset: 'naip'
