dataloader:
  _target_: earthtext.datamodules.chipmultilabel.ChipMultilabelModule
  metadata_file:     /opt/data/california-worldcover-chips/california-worldcover-chips-osm-multilabels.parquet
  embeddings_folder: /opt/data/california-worldcover-chips/embeddings_v0.2
  get_osm_strlabels: True
  #multilabel_threshold_osm_ohecount: 1
  get_osm_ohearea: True
  get_osm_ohecount: True
  get_osm_ohelength: True
  multilabel_threshold_osm_ohearea: 1000
  
model:
  _target_: earthtext.models.osmencoder.OSMEncoder
  input_dim: 297
  output_dim: 768
  layers_spec: [512, 512, 640]
  activation_fn: 'relu'
